services:
  minecraft-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minecraft-terminal
    networks:
      - minecraft-network  # Add to custom network
    ports:
      - "9867:2222"
    volumes:
      - ./.minecraft:/root/.minecraft
    environment:
      - MINECRAFT_SERVER_ADDRESS=minecraft-server  # Use service name directly
    depends_on:
      - minecraft-server

  minecraft-server:
    image: itzg/minecraft-server
    container_name: minecraft-server
    networks:
      - minecraft-network  # Add to custom network
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
      - TYPE=PAPER
      - MEMORY=2G
      - DIFFICULTY=normal
      - OVERRIDE_SERVER_PROPERTIES=true
      - ENABLE_WHITELIST=false
      - ONLINE_MODE=false
      - ALLOW_NETHER=true
    volumes:
      - ./minecraft_server_data:/data
    tty: true
    stdin_open: true
    restart: unless-stopped

networks:
  minecraft-network:
    driver: bridge
