[package]
name = "minecraft_terminal_viewer"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "termcast"
path = "src/bin/termcast.rs"

[lib]
name = "minecraft_terminal_viewer"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0"
crossterm = "0.29"
futures = "0.3.31"
image = "0.25"
libc = "0.2"
nix = { version = "0.30", features = ["signal"] }
pipe = "0.4"
rand_core = "0.6"
ratatui = "0.29"
reqwest = { version = "0.11", features = ["json"] }
russh = "0.52"
sha256 = "1.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
termwiz = "0.23"
tokio = { version = "1.45", features = ["full"] }
urlencoding = "2.1"
warp = "0.3"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
